import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requireSession } from "@/lib/auth";
import { formatIrishDate } from "@/lib/dates";
import { formatMoney } from "@/lib/money";
import { prisma } from "@/lib/prisma";

export default async function EmployeeDetailPage({ params }: { params: Promise<{ id: string }> }) { const [{ id }, session] = await Promise.all([params, requireSession()]); const employee = await prisma.employee.findFirst({ where: { id, companyId: session.companyId }, include: { projectLinks: { include: { project: true } }, timesheets: { orderBy: { date: "desc" }, take: 8, include: { project: true } }, payrollEntries: { orderBy: { createdAt: "desc" }, take: 5, include: { payrollPeriod: true } } } }); if (!employee) notFound(); return <><PageHeader eyebrow={employee.employeeId} title={employee.fullName} description={employee.email} actions={<><Link href="/employees" className={buttonVariants({ variant: "outline" })}>Back</Link><Link href={`/employees/${id}/edit`} className={buttonVariants()}>Edit employee</Link></>} /><div className="grid gap-6 lg:grid-cols-3"><Card><CardHeader><CardTitle>Employment</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><div><p className="text-muted-foreground">Status</p><StatusBadge status={employee.status} /></div><div><p className="text-muted-foreground">Payment type</p><p className="font-medium capitalize">{employee.paymentType.toLowerCase()}</p></div><div><p className="text-muted-foreground">Rate</p><p className="font-medium">{employee.paymentType === "HOURLY" ? `${formatMoney(employee.hourlyRate!.toString())} per hour` : `${formatMoney(employee.monthlySalary!.toString())} per month`}</p></div><div><p className="text-muted-foreground">Start date</p><p className="font-medium">{formatIrishDate(employee.startDate)}</p></div></CardContent></Card><Card><CardHeader><CardTitle>Assigned projects</CardTitle></CardHeader><CardContent><ul className="space-y-3">{employee.projectLinks.map(({ project }) => <li key={project.id}><Link className="text-sm font-medium hover:text-primary" href={`/projects/${project.id}`}>{project.name}</Link><p className="text-xs text-muted-foreground">{project.client}</p></li>)}</ul></CardContent></Card><Card><CardHeader><CardTitle>Recent payroll</CardTitle></CardHeader><CardContent><ul className="space-y-3">{employee.payrollEntries.map((entry) => <li key={entry.id} className="flex justify-between text-sm"><Link href={`/payroll/${entry.payrollPeriodId}`} className="hover:text-primary">{formatIrishDate(entry.payrollPeriod.payDate)}</Link><span className="font-medium">{formatMoney(entry.netPay.toString())}</span></li>)}</ul></CardContent></Card></div><Card className="mt-6"><CardHeader><CardTitle>Recent time entries</CardTitle></CardHeader><CardContent><div className="grid gap-2">{employee.timesheets.map((entry) => <div key={entry.id} className="flex justify-between border-b py-2 text-sm"><span>{formatIrishDate(entry.date)} · {entry.project.name}</span><span className="font-medium">{entry.hours.toString()}h</span></div>)}</div></CardContent></Card></>; }
