import type { Employee } from "@prisma/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toDateInput } from "@/lib/dates";

export function EmployeeForm({ employee, action }: { employee?: Employee; action: (formData: FormData) => Promise<void> }) {
  return <form action={action}><Card><CardContent className="grid gap-5 p-6 sm:grid-cols-2"><div className="form-field sm:col-span-2"><Label htmlFor="fullName">Full name</Label><Input id="fullName" name="fullName" defaultValue={employee?.fullName} required /></div><div className="form-field"><Label htmlFor="employeeId">Employee ID</Label><Input id="employeeId" name="employeeId" defaultValue={employee?.employeeId} required /></div><div className="form-field"><Label htmlFor="email">Email</Label><Input id="email" name="email" type="email" defaultValue={employee?.email} required /></div><div className="form-field"><Label htmlFor="phone">Phone <span className="text-muted-foreground">(optional)</span></Label><Input id="phone" name="phone" type="tel" defaultValue={employee?.phone ?? ""} /></div><div className="form-field"><Label htmlFor="startDate">Start date</Label><Input id="startDate" name="startDate" type="date" defaultValue={employee ? toDateInput(employee.startDate) : undefined} required /></div><div className="form-field"><Label htmlFor="paymentType">Payment type</Label><select id="paymentType" name="paymentType" className="native-select" defaultValue={employee?.paymentType ?? "HOURLY"}><option value="HOURLY">Hourly</option><option value="MONTHLY">Monthly</option></select></div><div className="form-field"><Label htmlFor="status">Status</Label><select id="status" name="status" className="native-select" defaultValue={employee?.status ?? "ACTIVE"}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></div><div className="form-field"><Label htmlFor="hourlyRate">Hourly rate (€)</Label><Input id="hourlyRate" name="hourlyRate" type="number" min="0" step="0.01" defaultValue={employee?.hourlyRate?.toString() ?? ""} /><p className="text-xs text-muted-foreground">Required only for hourly employees.</p></div><div className="form-field"><Label htmlFor="monthlySalary">Monthly salary (€)</Label><Input id="monthlySalary" name="monthlySalary" type="number" min="0" step="0.01" defaultValue={employee?.monthlySalary?.toString() ?? ""} /><p className="text-xs text-muted-foreground">Required only for monthly employees.</p></div><div className="flex justify-end sm:col-span-2"><Button type="submit" size="lg">{employee ? "Save changes" : "Create employee"}</Button></div></CardContent></Card></form>;
}
