import type { Employee, Project } from "@prisma/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toDateInput } from "@/lib/dates";

export function ProjectForm({ project, employees, assignedIds = [], action }: { project?: Project; employees: Employee[]; assignedIds?: string[]; action: (formData: FormData) => Promise<void> }) {
  return <form action={action}><Card><CardContent className="grid gap-5 p-6 sm:grid-cols-2"><div className="form-field"><Label htmlFor="name">Project name</Label><Input id="name" name="name" defaultValue={project?.name} required /></div><div className="form-field"><Label htmlFor="client">Client</Label><Input id="client" name="client" defaultValue={project?.client} required /></div><div className="form-field"><Label htmlFor="location">Location</Label><Input id="location" name="location" defaultValue={project?.location} required /></div><div className="form-field"><Label htmlFor="startDate">Start date</Label><Input id="startDate" name="startDate" type="date" defaultValue={project ? toDateInput(project.startDate) : undefined} required /></div><div className="form-field"><Label htmlFor="status">Status</Label><select id="status" name="status" className="native-select" defaultValue={project?.status ?? "ACTIVE"}><option value="ACTIVE">Active</option><option value="COMPLETED">Completed</option></select></div><div className="form-field sm:col-span-2"><Label htmlFor="notes">Notes</Label><Textarea id="notes" name="notes" defaultValue={project?.notes ?? ""} rows={4} /></div><fieldset className="sm:col-span-2"><legend className="mb-3 text-sm font-medium">Assigned employees</legend><div className="grid gap-2 rounded-xl border p-4 sm:grid-cols-2 lg:grid-cols-3">{employees.map((employee) => <label key={employee.id} className="flex items-center gap-2 text-sm"><input type="checkbox" name="employeeIds" value={employee.id} defaultChecked={assignedIds.includes(employee.id)} className="size-4 accent-[var(--primary)]" />{employee.fullName}</label>)}</div></fieldset><div className="flex justify-end sm:col-span-2"><Button type="submit" size="lg">{project ? "Save changes" : "Create project"}</Button></div></CardContent></Card></form>;
}
