# Generated by Django 5.2.17 on 2026-08-29 13:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('address', models.TextField()),
                ('currency', models.CharField(choices=[('EUR', 'EUR (€)')], default='EUR', max_length=3)),
                ('default_payroll_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=191)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('payment_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='payroll.company')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pay_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('FINALISED', 'Finalised')], db_index=True, default='DRAFT', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_periods', to='payroll.company')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=191)),
                ('employee_number', models.CharField(max_length=50)),
                ('payment_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('usc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('prsi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='payroll.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['employee_name'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=191)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('payroll_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payslip', to='payroll.payrollentry')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=191)),
                ('client', models.CharField(max_length=191)),
                ('location', models.CharField(max_length=191)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], db_index=True, default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='payroll.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_links', to='payroll.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_links', to='payroll.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(related_name='projects', through='payroll.ProjectEmployee', to='payroll.employee'),
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='payroll.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='payroll.project')),
            ],
            options={
                'ordering': ['-date', 'employee__full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('hourly_rate__gte', 0), ('hourly_rate__isnull', True), _connector='OR'), name='employee_hourly_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_salary__gte', 0), ('monthly_salary__isnull', True), _connector='OR'), name='employee_monthly_salary_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('company', 'frequency', 'start_date', 'end_date'), name='unique_payroll_period'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='payroll_period_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollentry',
            constraint=models.UniqueConstraint(fields=('period', 'employee'), name='unique_payroll_employee_period'),
        ),
        migrations.AddConstraint(
            model_name='payrollentry',
            constraint=models.CheckConstraint(condition=models.Q(('hours_worked__gte', 0)), name='payroll_hours_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payrollentry',
            constraint=models.CheckConstraint(condition=models.Q(('gross_pay__gte', 0)), name='payroll_gross_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payrollentry',
            constraint=models.CheckConstraint(condition=models.Q(('paye__gte', 0), ('usc__gte', 0), ('prsi__gte', 0), ('other_deductions__gte', 0)), name='payroll_deductions_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payrollentry',
            constraint=models.CheckConstraint(condition=models.Q(('total_deductions__lte', models.F('gross_pay'))), name='payroll_deductions_not_above_gross'),
        ),
        migrations.AddConstraint(
            model_name='payrollentry',
            constraint=models.CheckConstraint(condition=models.Q(('net_pay__gte', 0)), name='payroll_net_non_negative'),
        ),
        migrations.AddIndex(
            model_name='projectemployee',
            index=models.Index(fields=['employee', 'project'], name='payroll_pro_employe_c096fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectemployee',
            constraint=models.UniqueConstraint(fields=('project', 'employee'), name='unique_project_employee'),
        ),
        migrations.AddIndex(
            model_name='timesheetentry',
            index=models.Index(fields=['employee', 'date'], name='payroll_tim_employe_7b6d38_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheetentry',
            index=models.Index(fields=['project', 'date'], name='payroll_tim_project_a28992_idx'),
        ),
        migrations.AddConstraint(
            model_name='timesheetentry',
            constraint=models.CheckConstraint(condition=models.Q(('hours__gt', 0), ('hours__lte', 24)), name='timesheet_hours_valid'),
        ),
        migrations.AddConstraint(
            model_name='timesheetentry',
            constraint=models.UniqueConstraint(fields=('employee', 'project', 'date'), name='unique_timesheet_employee_project_date'),
        ),
    ]
